package com.authguard.e2e.suites.common

final class ContextKeys {
    public static final String domain = "domain"
    public static final String otaUsername = "otaUsername"
    public static final String otaPassword = "otaPassword"
    public static final String createdAccount = "createdAccount"
    public static final String createdApplication= "createdApplication"
    public static final String createdCredentials = "createdCredentials"
    public static final String accountIdentifiers = "identifiers"
    public static final String accountPassword = "password"
    public static final String adminAccount = "adminAccount"
    public static final String adminUsername = "adminUsername"
    public static final String adminPassword = "adminPassword"
    public static final String adminApp = "adminApp"
    public static final String baseUrl = "baseUrl"
    public static final String key = "key"
    public static final String idempotentKey = "idempotentKey"
    public static final String emailServer = "emailServer"
    public static final String accountRoleName = "accountRole"
    public static final String appRoleName = "appRole"
    public static final String permissionGroup = "permissionGroup"
    public static final String permissionName = "permissionName"
    public static final String app = "app"
    public static final String temporaryKey = "temporaryKey"
    public static final String token = "token"
    public static final String refreshToken = "refreshToken"
    public static final String oldRefreshToken = "oldRefreshToken"
    public static final String oldPassword = "oldPassword"
    public static final String oldIdentifier = "oldIdentifier"
    public static final String newIdentifier = "newIdentifier"
    public static final String authorizationCode = "authorizationCode"
    public static final String authorizationCodeRequestToken = "authorizationCodeRequestToken"
}
